### ISSUE TITLE
add: Jenkins@Rin integration by FourOfSeven

### ISSUE THREAD

**Issue by SenHeng** [thelegendofcode/AngularTypescriptWebpack#7]
### Prerequisites:
1. Tests
1. Somewhere to deploy to

**Comment by FourOfSeven** [comment]
![the-daleks](https://user-images.githubusercontent.com/25164707/27239304-54333452-530b-11e7-9f66-83673b289392.jpg)

**Comment by SenHeng** [comment]
This issue belongs in https://github.com/thelegendofcode/Continuum
